### ISSUE TITLE
How to Kubernetes configuration files?

### ISSUE THREAD

**Issue by shabanovve** [egoshard/intellij-k8s-runtime-config#2]
Hi! I use IntelliJ IDEA 2021.3.3 (Ultimate Edition)
I found "K8s Config"  and selected 'enable'.
But I didn't see any control for Kubernetes configuration files.
![2022-04-03_15-37](https://user-images.githubusercontent.com/2938082/161421852-85d9d209-d7dc-40f5-919b-842cfd328f79.png)
How to add Kubernetes configuration files?

**Comment by egoshard** [comment]
Sorry for the delay, the addition of the "Modify options" section in IntelliJ caused an issue with the enabled area. This is resolved in a patch that is already deployed into the marketplace.
