### ISSUE TITLE
2022.3.1 support ?

### ISSUE THREAD

**Issue by gberche-orange** [egoshard/intellij-k8s-runtime-config#4]
Thanks for contributing this plugin.

Trying it into 2022.3.1, I see no k8s config tab in the run/debug config, am I looking at the wrong location ?

![image](https://user-images.githubusercontent.com/4748380/210535329-943550b2-bcca-4aaf-89ab-f17fb25f0034.png)

**Comment by aviramha** [comment]
I think the plugin is no longer maintained.. I believe that you can get similar feature from https://github.com/metalbear-co/mirrord

**Comment by gberche-orange** [comment]
thanks @aviramha !
